# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]  # Test this version of node.js

    steps:
    - uses: actions/checkout@v2  # Bring the source code into the current working directory
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci  # Do a clean install of the node dependencies
    - run: npm run build --if-present
    - run: npm test
      env:  # Set environment variables
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        jwtSecret: ${{ secrets.jwtSecret }}
